### PR TITLE
implement reset

### LINKED ISSUE #180: Allow to Re-fetch all data when using smart listStrategy
After a socket reconnection, It would be useful to tell the client to forget all local data and fetch fresh data from the server again when using smart list strategy.
Can we implement such a refresh method on the service, or even better directly on the feathers client (which would trigger a refresh on all observers) ?

### PR DESCRIPTION
**Pull request by rmanibus**
### Summary
This add a method which allow to fetch fresh data from the server in smart mode.
 fix #180

### CODE REVIEW

**Comment by rmanibus** [comment]
Can someone review this ?

**Comment by daffl** [comment]
I think this make sense but probably should also have some documentation added to the Readme.

**Comment by rmanibus** [comment]
> 
> 
> I think this make sense but probably should also have some documentation added to the Readme.

done

**Comment by rmanibus** [comment]
@daffl Can you please review this ?

**Pull request merged**
